# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AssessRFC
                                 A QGIS plugin
 Assess Random Forest Classifier (RFC)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-03-19
        copyright            : (C) 2018 by Luis Fernando Chimelo Ruiz
        email                : ruiz.ch@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AssessRFC class from file AssessRFC.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .assess_rfc import AssessRFC
    return AssessRFC(iface)
